language: python

python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "pypy"
    - "pypy3"

env:
  - SQLALCHEMY_VERSION=1.2.3
  - SQLALCHEMY_VERSION=1.3.24
  - SQLALCHEMY_VERSION=1.4.99


install:
    - pip install "SQLAlchemy <= $SQLALCHEMY_VERSION"
    - pip install -e .[testing]

script:
    - nosetests
