name: run

on: [push]

jobs:
  tests_old_env:
    # "ubuntu-latest" does not have Python 3.6
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.6, "pypy-2.7"]
        sqlalchemy-version: [1.2, 1.3, 1.4]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install "SQLAlchemy == ${{ matrix.sqlalchemy-version }}.*"
        pip install -e .[testing]
        pip install pytest

    - name: Run test suite
      run: |
        pytest


  tests_new_env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11", "pypy-3.9"]
        sqlalchemy-version: [1.4, 2.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install "SQLAlchemy == ${{ matrix.sqlalchemy-version }}.*"
        pip install -e .[testing]
        pip install pytest

    - name: Run test suite
      run: |
        pytest
