name: run

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, "3.10", "pypy-2.7", "pypy-3.6"]
        sqlalchemy-version: [1.2, 1.3, 1.4]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install "SQLAlchemy == ${{ matrix.sqlalchemy-version }}.*"
        pip install -e .[testing]
        pip install nose2

    - name: Run test suite
      run: |
        nose2

